# Generated by Django 3.2.13 on 2023-02-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
