# Generated by Django 3.2.13 on 2023-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='first_part',
            field=models.BooleanField(default=True),
        ),
    ]
