# Generated by Django 3.2.13 on 2023-02-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_first_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id_challonge',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
