# Generated by Django 3.2.13 on 2022-11-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_match_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id_challonge',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='matches',
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='player.tournament'),
            preserve_default=False,
        ),
    ]
