# Generated by Django 3.2.13 on 2023-01-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='player',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
